
server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true  # JSP 재컴파일 허용
        
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true



